drive {
  folder-ids = ${?DRIVE_FOLDER_IDS}
  client-id = ${?DRIVE_CLIENT_ID}
  client-secret = ${?DRIVE_CLIENT_SECRET}
  auth-redirect-port = 8085
}

sync {
  interval = 1 hour
  variant-priority = ["(merged)", "", "(as)"]
  parallel-downloads = 1
}

storage {
  videos-dir = "data/videos"
  db-path = "data/app.db"
}

http {
  host = "127.0.0.1"
  port = 8080
}
